# Generated by Django 4.1.3 on 2022-12-01 11:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_alter_note_content_alter_note_title'),
    ]

    operations = [
        migrations.RenameField(
            model_name='note',
            old_name='background_image',
            new_name='background',
        ),
        migrations.RemoveField(
            model_name='note',
            name='background_color',
        ),
        migrations.AddField(
            model_name='note',
            name='color',
            field=models.CharField(blank=True, max_length=7),
        ),
    ]
